version: '3'
services:

  backend:
    image: openjdk:11
    ports:
      - "8081:8080"
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app/backend
    command: './mvnw spring-boot:run'
